const characters = {
	jx_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jx_rende", "jijiang"],
		isZhugong: true,
	},
	jx_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jx_wusheng", "yijue"],
	},
	jx_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jx_paoxiao", "tishen"],
	},
	jx_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["jx_guanxing", "kongcheng"],
	},
	jx_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["longdan", "yajiao"],
	},
	jx_machao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "jx_tieji"],
	},
	jx_huangyueying: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["jx_jizhi", "jx_qicai"],
	},
	jx_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jx_zhiheng", "jx_jiuyuan"],
		isZhugong: true,
	},
	jx_ganning: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qixi"],
	},
	jx_lvmeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["keji"],
	},
	jx_huanggai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["kurou"],
	},
	jx_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["yingzi", "fanjian"],
	},
	jx_daqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["guose", "liuli"],
	},
	jx_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["qianxun", "lianying"],
	},
	jx_sunshangxiang: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["jieyin", "xiaoji"],
	},
	jx_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jianxiong", "hujia"],
		isZhugong: true,
	},
	jx_simayi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["fankui", "guicai"],
	},
	jx_xiahoudun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["ganglie"],
	},
	jx_zhangliao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["tuxi"],
	},
	jx_xuchu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["luoyi"],
	},
	jx_guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["tiandu", "yiji"],
	},
	jx_zhenji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["qingguo", "luoshen"],
	},
	jx_huatuo: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jijiu", "qingnang"],
	},
	jx_lvbu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["wushuang"],
	},
	jx_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["lijian", "biyue"],
	},
	jx_huaxiong: {
		sex: "male",
		group: "qun",
		hp: 6,
		skills: ["yaowu"],
	},
	jx_gongsunzan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yicong"],
	},
	jx_panfeng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["kuangfu"],
	},
	jx_ganfuren: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["shenzhi", "shushen"],
	},
	jx_yuejin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["xiaoguo"],
	},
};

export default characters;
