const characters = {
  // 起
  jsrg_kongrong: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jsrglirang", "zhengyi"],
    dieAudios: ["kongrong"],
  },
  jsrg_caocao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgzhenglve", "jsrghuilie"],
  },

  jsrg_liuhong: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgchaozheng", "jsrgshenchong", "jsrgjulian"],
    isZhugong: true,
  },
  jsrg_wangyun: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jsrgshelun", "jsrgfayi"],
    clans: ["太原王氏"],
  },
  jsrg_huangfusong: {
    sex: "male",
    group: "qun",
    hp: 4,
    names: "皇甫|嵩",
    skills: ["jsrgguanhuo", "jsrg_new_juxia"],
  },
  jsrg_qiaoxuan: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jsrg_new_juezhi", "jsrgjizhao"],
  },
  jsrg_xushao: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["sbyingmen", "sbpingjian"],
  },
  jsrg_hejin: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgzhaobing", "jsrgzhuhuan", "jsrgyanhuo"],
  },
  jsrg_dongbai: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["jsrgshichong", "jsrg_new_lianzhu"],
    img: "image/character/dongbai.jpg",
  },
  jsrg_nanhualaoxian: {
    sex: "male",
    group: "qun",
    hp: 3,
    names: "庄|周",
    skills: ["jsrgshoushu", "jsrgxundao", "jsrglinghua"],
    img: "image/character/nanhualaoxian.jpg",
  },
  jsrg_yangbiao: {
    sex: "male",
    group: "qun",
    hp: 3,
    maxHp: 4,
    skills: ["jsrgzhaohan", "jsrgrangjie", "jsrgyizheng"],
    img: "image/character/yangbiao.jpg",
    dieAudios: ["yangbiao"],
    clans: ["弘农杨氏"],
  },
  ol_wangrong: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["olfengzi", "oljizhan", "olfusong"],
  },
  duanwei: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["junklangmie"],
  },
  jsrg_zhujun: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgfendi", "jsrgjuxiang"],
  },
  jsrg_liuyan: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["xinfu_limu", "jsrgtushe", "jsrgtongjue"],
    isZhugong: true,
    img: "image/character/liuyan.jpg",
    dieAudios: ["liuyan"],
  },
  jsrg_liubei: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgjishan", "jsrgzhenqiao"],
  },
  jsrg_sunjian: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgpingtao", "jsrgjuelie"],
  },
  // 承
  jsrg_chendeng: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jsrglunshi", "jsrgguitu"],
  },
  jsrg_guanyu: {
    sex: "male",
    group: "shu",
    hp: 5,
    skills: ["jsrgguanjue", "jsrgnianen"],
    groupBorder: "wei",
  },
  jsrg_zoushi: {
    sex: "female",
    group: "qun",
    hp: 3,
    names: "邹|null",
    skills: ["jsrgguyin", "jsrgzhangdeng"],
  },
  zhenmi: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["jsrgjixiang", "jsrgchengxian"],
  },
  jsrg_zhanghe: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jsrgqiongtu", "jsrgxianzhu"],
    doubleGroup: ["wei", "qun"],
  },
  jsrg_zhangliao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgzhengbing", "jsrgtuwei"],
    doubleGroup: ["wei", "qun"],
  },
  jsrg_xuyou: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["jsrglipan", "jsrgqingxi", "jsrgjinmie"],
    doubleGroup: ["wei", "qun"],
  },
  jsrg_lvbu: {
    sex: "male",
    group: "qun",
    hp: 5,
    skills: ["jsrgwuchang", "jsrgqingjiao", "jsrgchengxu"],
    doubleGroup: ["shu", "qun"],
  },
  jsrg_chunyuqiong: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgcangchu", "jsrgshishou"],
    img: "image/character/re_chunyuqiong.jpg",
    dieAudios: ["re_chunyuqiong"],
    names: "淳于|琼",
  },
  jsrg_xugong: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["jsrgbiaozhao", "jsrgyechou"],
    img: "image/character/re_xugong.jpg",
  },
  jsrg_sunce: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["jsrgduxing", "jsrgzhiheng", "jsrgzhasi", "jsrgbashi"],
    isZhugong: true,
  },
  // 转
  jsrg_zhangfei: {
    sex: "male",
    group: "shu",
    hp: 5,
    skills: ["jsrgbaohe", "jsrgxushi"],
  },
  jsrg_machao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgzhuiming", "mashu"],
  },
  jsrg_lougui: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["jsrgshacheng", "jsrgninghan"],
  },
  jsrg_zhangren: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgfuni", "jsrgchuanxin"],
  },
  jsrg_huangzhong: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["jsrgcuifeng", "jsrgdengnan"],
  },
  jsrg_xiahourong: {
    sex: "male",
    group: "wei",
    hp: 4,
    names: "夏侯|荣",
    skills: ["jsrgfenjian"],
  },
  jsrg_sunshangxiang: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["jsrgguiji", "jsrgjiaohao"],
  },
  jsrg_pangtong: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jsrgmanjuan", "jsrgyangming"],
  },
  jsrg_hansui: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgniluan", "jsrghuchou", "jsrgjiemeng"],
    isZhugong: true,
    img: "image/character/xin_hansui.jpg",
  },
  jsrg_zhangchu: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["jsrghuozhong", "jsrgrihui"],
    dieAudios: ["zhangchu"],
  },
  jsrg_xiahouen: {
    sex: "male",
    group: "wei",
    hp: 4,
    names: "夏侯|恩",
    skills: ["jsrghujian", "jsrgshili"],
    img: "image/character/tw_xiahouen.jpg",
    dieAudios: ["tw_xiahouen"],
  },
  jsrg_guojia: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["jsrgqingzi", "jsrgdingce", "jsrgzhenfeng"],
  },
  jsrg_fanjiangzhangda: {
    sex: "male",
    group: "wu",
    hp: 5,
    names: "范|强-张|达",
    skills: ["jsrgfushan"],
    img: "image/character/fanjiangzhangda.jpg",
  },
  // 合
  jsrg_zhugeliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    names: "诸葛|亮",
    skills: ["jsrgwentian", "jsrgchushi", "jsrgyinlve"],
  },
  jsrg_jiangwei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["jsrgjinfa", "jsrgfumou", "jsrgxuanfeng"],
    groupBorder: "wei",
  },
  jsrg_simayi: {
    sex: "male",
    group: "wei",
    hp: 4,
    names: "司马|懿",
    skills: ["jsrgyingshi", "jsrgtuigu"],
  },
  jsrg_caofang: {
    sex: "male",
    group: "wei",
    hp: 3,
    maxHp: 4,
    skills: ["jsrgzhaotu", "jsrgjingju", "jsrgweizhui"],
    isZhugong: true,
  },
  jsrg_sunjun: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["jsrgyaoyan", "jsrgbazheng"],
  },
  jsrg_luxun: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["jsrgyoujin", "jsrgdailao", "jsrgzhubei"],
    clans: ["吴郡陆氏"],
  },
  jsrg_guoxun: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jsrgeqian", "jsrgfusha"],
  },
  jsrg_sunlubansunluyu: {
    sex: "female",
    group: "wu",
    hp: 3,
    names: "孙|鲁班-孙|鲁育",
    skills: ["jsrgdaimou", "jsrgfangjie"],
  },
  jsrg_zhaoyun: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["jsrglonglin", "jsrgzhendan"],
  },
  jsrg_gaoxiang: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["jsrgchiying"],
    dieAudios: ["gaoxiang"],
  },
  jsrg_liuyong: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["jsrgdanxin", "jsrgfengxiang"],
    dieAudios: ["liuyong"],
  },
  jsrg_weiwenzhugezhi: {
    sex: "male",
    group: "wu",
    hp: 4,
    names: "卫|温-诸葛|直",
    skills: ["jsrgfuhai"],
    img: "image/character/re_weiwenzhugezhi.jpg",
    dieAudios: ["weiwenzhugezhi"],
  },
  jsrg_zhangxuan: {
    sex: "female",
    group: "wu",
    hp: 4,
    skills: ["jsrgtongli", "jsrgshezang"],
    img: "image/character/zhangxuan.jpg",
    dieAudios: ["zhangxuan"],
  },
  jsrg_guozhao: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["jsrgpianchong", "jsrgzunwei"],
    img: "image/character/guozhao.jpg",
    dieAudios: ["guozhao"],
  },
  // 衰
  jsrg_liubiao: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jsrgyansha", "jsrgqingping"],
  },
  jsrg_zhangjiao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgxiangru", "jsrgwudao"],
  },
  jsrg_yangqiu: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["mbsaojian"],
  },
  jsrg_yuanshao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgzhimeng", "jsrgtianyu", "jsrgzhuni", "jsrghezhi"],
    isZhugong: true,
  },
  jsrg_zhanghuan: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgzhushou", "jsrgyangge"],
  },
  jsrg_caojiewangfu: {
    sex: "male",
    group: "qun",
    hp: 3,
    names: "曹|节-王|甫",
    skills: ["jsrgzonghai", "jsrgjueyin"],
  },
  jsrg_zhangju: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgqiluan", "jsrgxiangjia"],
  },
  jsrg_chenfan: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jsrggangfen", "jsrgdangren"],
  },
  jsrg_songhuanghou: {
    sex: "female",
    group: "qun",
    hp: 3,
    names: "宋|null",
    skills: ["jsrgzhongzen", "jsrgxuchong"],
  },
  jsrg_dongzhuo: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgguanshi", "jsrgcangxiong", "jsrgjiebing"],
  },
  jsrg_yl_luzhi: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jsrgruzong", "jsrgdaoren"],
  },
  // 兴
  jsrg_tufashujineng: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jsrgqinrao", "jsrgfuran"],
    names: "秃发|树机能",
  },
  jsrg_dengai: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jsrgpiqi", "jsrgzhoulin"],
  },
  jsrg_limi: {
    sex: "male",
    group: "shu",
    groupBorder: "jin",
    hp: 3,
    skills: ["jsrgciyin", "jsrgchendu"],
  },
  jsrg_wangjun: {
    sex: "male",
    group: "jin",
    hp: 4,
    skills: ["jsrgchengliu", "jsrgjianlou"],
  },
  jin_jsrg_simazhao: {
    sex: "male",
    group: "jin",
    isZhugong: true,
    hp: 4,
    isUnseen: true,
    skills: ["jsrgweisi", "jsrgxiezheng", "jsrgdangyi"],
    names: "司马|昭",
  },
  jsrg_simazhao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jsrgqiantun", "jsrgxiezheng", "jsrgzhaoxiong"],
    names: "司马|昭",
  },
  jsrg_zhugedan: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jsrgzuozhan", "jsrgcuibing", "jsrglangan"],
    names: "诸葛|诞",
  },
  jsrg_lukang: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["jsrgzhuwei", "jsrgkuangjian"],
    clans: ["吴郡陆氏"],
  },
  jsrg_wenyang: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jsrgfuzhen"],
  },
  simaliang: {
    sex: "male",
    group: "jin",
    hp: 3,
    maxHp: 4,
    skills: ["sheju", "zuwang"],
    names: "司马|亮",
  },
  malong: {
    sex: "male",
    group: "jin",
    hp: 4,
    skills: ["fennan", "xunji"],
  },
  jiananfeng: {
    sex: "female",
    group: "jin",
    hp: 3,
    skills: ["shanzheng", "xiongbao", "liedu"],
  },
}

export default characters
