const characterSort = {
  jiangshanrugu_qi: [
    "jsrg_caocao",

    "jsrg_liuhong",
    "jsrg_wangyun",
    "jsrg_huangfusong",
    "jsrg_qiaoxuan",
    "jsrg_xushao",
    "jsrg_hejin",
    "jsrg_dongbai",
    "jsrg_nanhualaoxian",
    "jsrg_yangbiao",
    "jsrg_kongrong",
    "ol_wangrong",
    "duanwei",
    "jsrg_zhujun",
    "jsrg_liuyan",
    "jsrg_liubei",
    "jsrg_sunjian",
  ],
  jiangshanrugu_cheng: [
    "jsrg_chendeng",
    "jsrg_guanyu",
    "jsrg_zoushi",
    "zhenmi",
    "jsrg_zhanghe",
    "jsrg_zhangliao",
    "jsrg_xuyou",
    "jsrg_lvbu",
    "jsrg_quyi",
    "jsrg_caosong",
    "yuantanyuanshang",
    "yanfuren",
    "gaolan",
    "jsrg_taoqian",
    "jsrg_chunyuqiong",
    "jsrg_xugong",
    "jsrg_sunce",
  ],
  jiangshanrugu_zhuan: [
    "jsrg_zhangfei",
    "jsrg_machao",
    "jsrg_lougui",
    "jsrg_zhangren",
    "jsrg_huangzhong",
    "jsrg_xiahourong",
    "jsrg_sunshangxiang",
    "jsrg_pangtong",
    "caimaozhangyun",
    "jianggan",
    "huangchengyan",
    "jsrg_kanze",
    "jsrg_hansui",
    "jsrg_zhangchu",
    "jsrg_xiahouen",
    "jsrg_guojia",
    "jsrg_fanjiangzhangda",
  ],
  jiangshanrugu_he: [
    "jsrg_zhugeliang",
    "jsrg_jiangwei",
    "jsrg_simayi",
    "jsrg_caofang",
    "jsrg_sunjun",
    "jsrg_luxun",
    "jsrg_guoxun",
    "jsrg_sunlubansunluyu",
    "jsrg_zhaoyun",
    "caoshuang",
    "jsrg_wenqin",
    "jsrg_gaoxiang",
    "jsrg_liuyong",
    "jsrg_weiwenzhugezhi",
    "jsrg_zhangxuan",
    "chentai",
    "jsrg_guozhao",
  ],
  jiangshanrugu_shuai: [
    "jsrg_liubiao",
    "jsrg_zhangjiao",
    "jsrg_yangqiu",
    "jsrg_yuanshao",
    "jsrg_zhanghuan",
    "jsrg_caojiewangfu",
    "jsrg_zhangju",
    "jsrg_chenfan",
    "jsrg_songhuanghou",
    "jsrg_dongzhuo",
    "jsrg_yl_luzhi",
  ],
  jiangshanrugu_xing: [
    "jsrg_tufashujineng",
    "jsrg_dengai",
    "jsrg_limi",
    "jsrg_wangjun",
    "jin_jsrg_simazhao",
    "jsrg_simazhao",
    "jsrg_zhugedan",
    "jsrg_lukang",
    "jsrg_wenyang",
    "simaliang",
    "malong",
    "jiananfeng",
  ],
}

const characterSortTranslate = {
  jiangshanrugu_qi: "江山如故·起",
  jiangshanrugu_cheng: "江山如故·承",
  jiangshanrugu_zhuan: "江山如故·转",
  jiangshanrugu_he: "江山如故·合",
  jiangshanrugu_shuai: "江山如故·兴衰上",
  jiangshanrugu_xing: "江山如故·兴衰下",
}

export { characterSort, characterSortTranslate }
