window.wtk_character_replace = {
  caocao: [
    "caocao",
    "old_caocao",
    "re_caocao",
    "ol_caocao",
    "sb_caocao",
    "scl_caocao",
  ],
  simayi: ["simayi", "re_simayi", "ol_simayi"],
  xiahoudun: ["xiahoudun", "old_xiahoudun", "re_xiahoudun", "ol_xiahoudun"],
  zhangliao: ["zhangliao", "old_zhangliao", "re_zhangliao", "ol_zhangliao"],
  xuzhu: ["xuzhu", "old_xuzhu", "re_xuzhu", "ol_xuzhu"],
  guojia: ["guojia", "old_guojia", "re_guojia", "ol_guojia"],
  zhenji: ["zhenji", "re_zhenji", "ol_zhenji"],
  liubei: ["liubei", "old_liubei", "re_liubei", "ol_liubei"],
  guanyu: ["guanyu", "old_guanyu", "re_guanyu", "ol_guanyu"],
  zhangfei: ["zhangfei", "old_zhangfei", "re_zhangfei", "ol_zhangfei"],
  zhugeliang: ["zhugeliang", "re_zhugeliang", "ol_zhugeliang"],
  zhaoyun: ["zhaoyun", "old_zhaoyun", "re_zhaoyun", "ol_zhaoyun"],
  machao: ["machao", "re_machao", "ol_machao"],
  huangyueying: [
    "huangyueying",
    "old_huangyueying",
    "re_huangyueying",
    "ol_huangyueying",
  ],
  sunquan: ["sunquan", "re_sunquan", "ol_sunquan"],
  ganning: ["ganning", "re_ganning", "ol_ganning"],
  lvmeng: ["lvmeng", "re_lvmeng", "ol_lvmeng"],
  huanggai: ["huanggai", "re_huanggai", "ol_huanggai"],
  zhouyu: ["zhouyu", "re_zhouyu", "ol_zhouyu"],
  daqiao: ["daqiao", "re_daqiao", "ol_daqiao"],
  luxun: ["luxun", "re_luxun", "ol_luxun"],
  sunshangxiang: ["sunshangxiang", "re_sunshangxiang", "ol_sunshangxiang"],
  huatuo: ["huatuo", "re_huatuo", "ol_huatuo"],
  lvbu: ["lvbu", "old_lvbu", "re_lvbu", "ol_lvbu"],
  diaochan: ["diaochan", "old_diaochan", "re_diaochan", "ol_diaochan"],
  huaxiong: ["huaxiong", "re_huaxiong", "ol_huaxiong"],
  gongsunzan: ["gongsunzan", "re_gongsunzan", "ol_gongsunzan"],

  caoren: ["caoren", "re_caoren", "ol_caoren"],
  xiahouyuan: ["xiahouyuan", "re_xiahouyuan", "ol_xiahouyuan"],

  hetaihou: ["hetaihou", "ol_hetaihou"],

  tianshangyi: ["tianshangyi", "re_tianshangyi"],
}
