export default {
  "#rejianxiong1": "乱世天下，能者居之！",
  "#rejianxiong2": "宁人负我，毋人负我！",
  "#hujia_re_caocao1": "来人，来人！",
  "#hujia_re_caocao2": "有刺客！",
  "#re_caocao:die": "神龟虽寿，犹有竟时。",

  "#refankui1": "哼！正中下怀！",
  "#refankui2": "哼！自作孽不可活！",
  "#reguicai1": "天命难违？哈哈哈哈哈哈！",
  "#reguicai2": "才通天地，逆天改命！",
  "#re_simayi:die": "我的气数就到这里了么？",

  "#reganglie1": "哪个敢动我！",
  "#reganglie2": "伤我者，十倍奉还！",
  "#qingjian1": "福生于清俭，德生于卑退。",
  "#qingjian2": "钱财乃身外之物。",
  "#re_xiahoudun:die": "诸多败绩，有负丞相重托。",

  "#retuxi1": "快马突袭，占尽先机！",
  "#retuxi2": "马似飞影，枪如霹雳！",
  "#re_zhangliao:die": "被敌人占了先机，呃啊~",

  "#reluoyi1": "废话少说，放马过来吧！",
  "#reluoyi2": "过来打一架，对，就是你！",
  "#re_xuzhu:die": "丞相，末将尽力了！",

  "#tiandu_re_guojia1": "那，就这样吧。",
  "#tiandu_re_guojia2": "天意如此。",
  "#reyiji1": "锦囊妙策，终定社稷。",
  "#reyiji2": "依此计行，辽东可定。",
  "#re_guojia:die": "咳咳咳咳咳……",

  "#reluoshen1": "屏翳收风，川后静波。",
  "#reluoshen2": "冯夷鸣鼓，女娲清歌。",
  "#reqingguo1": "肩若削成，腰如约素。",
  "#reqingguo2": "延颈秀项，皓质呈露。",
  "#re_zhenji:die": "出亦复何苦，入亦复何愁。",

  "#rerende1": "同心同德，救困扶危！",
  "#rerende2": "施仁布泽，乃我大汉立国之本！",
  "#rejijiang1": "哪位将军替我拿下此贼？",
  "#rejijiang2": "欺我军无人乎？",
  "#re_liubei:die": "汉室未兴，祖宗未耀，朕实不忍此时西去……",

  "#rewusheng1": "逆贼，哪里走？！",
  "#rewusheng2": "刀锋所向，战无不克。",
  "#yijue1": "恩已断，义当绝！",
  "#yijue2": "关某向来恩怨分明。",
  "#re_guanyu:die": "桃园一拜，恩义长在。",

  "#repaoxiao1": "喝啊~",
  "#repaoxiao2": "今，必斩汝马下！",
  "#tishen1": "欺我无谋？定要汝等血偿！",
  "#tishen2": "谁，还敢过来一战？！",
  "#re_zhangfei:die": "桃园一拜，此生无憾！",

  "#reguanxing1": "天星之变，吾窥探一二。",
  "#reguanxing2": "星途莫测，细细推敲。",
  "#kongcheng_re_zhugeliang1": "淡然相对，转危为安。",
  "#kongcheng_re_zhugeliang2": "绝处逢生，此招慎用。",
  "#re_zhugeliang:die": "穷尽毕生，有憾无悔。",

  "#relongdan1": "进退自如，游刃有余。",
  "#relongdan2": "龙威虎胆，斩敌破阵！",
  "#yajiao1": "遍寻天下，但求一败。",
  "#yajiao2": "策马趋前，斩敌当先！",
  "#re_zhaoyun:die": "你们谁…还敢…再上…",

  "#retieji1": "敌人阵型已乱，随我杀！",
  "#retieji2": "目标敌阵，全军突击！",
  "#re_machao:die": "请将我，葬在西凉。",

  "#rejizhi1": "得上通，智集心。",
  "#rejizhi2": "集万千才智，致巧趣鲜用。",
  "#reqicai1": "女子之才，蕙质兰心。",
  "#reqicai2": "吾之才学，不逊先生分毫。",
  "#re_huangyueying:die": "我的面容，有吓到你吗？",

  "#rezhiheng1": "不急不躁，稳谋应对。",
  "#rezhiheng2": "制衡互牵，大局可安。",
  "#rejiuyuan1": "你们真是朕的得力干将。",
  "#rejiuyuan2": "有爱卿在，朕无烦忧。",
  "#re_sunquan:die": "锦绣江东，岂能失于我手？",

  "#qixi_re_ganning1": "弟兄们，准备动手！",
  "#qixi_re_ganning2": "你用不了这么多了！",
  "#fenwei1": "哼！敢欺我东吴无人！",
  "#fenwei2": "奋勇当先，威名远扬！",
  "#re_ganning:die": "别管我，继续杀。",

  "#keji_re_lvmeng1": "蓄力待时，不争首功。",
  "#keji_re_lvmeng2": "最好的机会，还在等着我。",
  "#qinxue1": "勤以修身，学以报国。",
  "#qinxue2": "兵书熟读，了然于胸。",
  "#gongxin_re_lvmeng1": "洞若观火，运筹帷幄。",
  "#gongxin_re_lvmeng2": "哼，早知如此。",
  "#re_lvmeng:die": "你，给我等着。",

  "#rekurou1": "我这把老骨头，不算什么。",
  "#rekurou2": "为成大义，死不足惜！",
  "#zhaxiang1": "铁索连舟而行，东吴水师可破！",
  "#zhaxiang2": "两军阵前，不斩降将！",
  "#re_huanggai:die": "盖，有负公瑾重托……",

  "#reyingzi1": "伯符，且看我这一手！",
  "#reyingzi2": "哈哈哈哈哈哈哈哈！",
  "#refanjian1": "抉择吧，在苦与痛的地狱中！",
  "#refanjian2": "与我为敌，就当这般生不如死！",
  "#re_zhouyu:die": "既生瑜，何生亮！既生瑜，何生亮！！",

  "#reguose1": "旅途劳顿，请下马休整吧~",
  "#reguose2": "还没到休息的时候！",
  "#liuli_re_daqiao1": "帮帮人家嘛~",
  "#liuli_re_daqiao2": "伯符不在身边，我要自己保重！",
  "#re_daqiao:die": "伯符，再也没人能欺负我了……",

  "#reqianxun1": "谦谦君子，温润如玉。",
  "#reqianxun2": "满招损，谦受益。",
  "#relianying1": "生生不息，源源不绝。",
  "#relianying2": "失之淡然，得之坦然。",
  "#re_luxun:die": "我的未竟之业……",

  "#rejieyin1": "得遇夫君，妾身福分。",
  "#rejieyin2": "随夫嫁娶，宜室宜家。",
  "#rexiaoji1": "剑利弓急，你可打不过我的。",
  "#rexiaoji2": "我会的武器，可多着呢。",
  "#re_sunshangxiang:die": "哎呀，这次弓箭射歪了。",

  "#jijiu_re_huatuo1": "妙手仁心，药到病除。",
  "#jijiu_re_huatuo2": "救死扶伤，悬壶济世。",
  "#chuli1": "病入膏肓，需下猛药。",
  "#chuli2": "病去，如抽丝。",
  "#re_huatuo:die": "生老病死，命不可违。",

  "#wushuang_re_lvbu1": "还有哪个敢挑战我？",
  "#wushuang_re_lvbu2": "三个齐上，也不是我的对手！",
  "#liyu1": "大丈夫，相时而动。",
  "#liyu2": "人不为己，天诛地灭。",
  "#re_lvbu:die": "我竟然输了…不可能！",

  "#lijian_re_diaochan1": "呵呵，你们都该死！",
  "#lijian_re_diaochan2": "你们，谁更爱我呢？",
  "#rebiyue1": "嗯~~再给人家一张，好不好嘛！",
  "#rebiyue2": "美人本该有此福利！",
  "#re_diaochan:die": "父亲之恩，貂蝉来生再报。",

  "#reyaowu1": "别得意的太早。",
  "#reyaowu2": "黄毛小儿，就这两下子吗？",
  "#re_huaxiong:die": "皮厚不挡刀哇……",

  "#qiaomeng1": "夺敌辎重，以为己用。",
  "#qiaomeng2": "秣马厉兵，枕戈待战。",
  "#yicong_re_gongsunzan1": "列阵锋矢，直取要害。",
  "#yicong_re_gongsunzan2": "变阵冲轭，以守代攻。",
  "#re_gongsunzan:die": "皇图霸业梦，付之，一炬中……",

  "#jiangchi1": "谨遵父训，不可逞匹夫之勇。",
  "#jiangchi2": "吾定当身先士卒，振魏武雄风！",
  "#caozhang:die": "子桓，你害我。",

  "#jijie1": "一拜一起，未足为劳。",
  "#jijie2": "识言观行，方能雍容风议。",
  "#jiyuan1": "公若辞，必遭蔡瑁之害矣。",
  "#jiyuan2": "形势危急，还请速行。",
  "#re_yiji:die": "未能，救得刘公脱险……",
}
