export default {
  ol_caoren: "殊死据守",
  ol_xiahouyuan: "疾行的猎豹",
  ol_huangzhong: "老当益壮",
  ol_weiyan: "嗜血的独狼",
  ol_xiaoqiao: "矫情之花",
  ol_zhoutai: "护主周全",
  ol_zhangjiao: "天公将军",
  ol_yuji: "太平道人",
  ol_shen_guanyu: "血海罗刹",
  ol_shen_lvmeng: "兼资文武",

  ol_dianwei: "古之恶来",
  ol_xunyu: "王佐之才",
  ol_sp_zhugeliang: "卧龙",
  ol_pangtong: "凤雏",
  ol_taishici: "笃烈之士",
  ol_pangde: "人马一体",
  ol_yuanshao: "高贵的名门",
  ol_yanwen: "虎狼兄弟",
  ol_shen_zhouyu: "合纵破曹",
  ol_shen_zhugeliang: "合纵破曹",

  ol_caopi: "魏王称帝",
  ol_xuhuang: "周亚夫之风",
  ol_zhurong: "野性的女王",
  ol_menghuo: "南蛮王",
  ol_lusu: "独断的外交家",
  ol_sunjian: "武烈帝",
  ol_dongzhuo: "魔王",
  ol_jiaxu: "冷酷的毒士",
  ol_shen_lvbu: "监兵噬魅",
  ol_shen_caocao: "玄天通冥",

  ol_dengai: "矫然的壮士",
  ol_zhanghe: "料敌机先",
  ol_jiangwei: "龙的衣钵",
  ol_liushan: "无为的真命主",
  ol_sunce: "江东的小霸王",
  ol_zhangzhang: "经天纬地",
  ol_zuoci: "迷之仙人",
  ol_caiwenji: "异乡的孤女",
  ol_shen_simayi: "徐图大略",
  ol_shen_zhaoyun: "神龙天降",
}
