const characters = {
	huangzhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["liegong"],
	},
	weiyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["kuanggu"],
	},
	xiahouyuan: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["shensu"],
	},
	caoren: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jushou"],
	},
	xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["tianxiang", "hongyan"],
	},
	zhoutai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["buqu"],
	},
	zhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["leiji", "guidao", "huangtian"],
		isZhugong: true,
	},
	yuji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["guhuo"],
	},
	dianwei: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qiangxi"],
	},
	xunyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["quhu", "jieming"],
	},
	pangtong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["lianhuan", "niepan"],
	},
	wolongzhuge: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["huoji", "bazhen", "kanpo"],
	},
	taishici: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["tianyi"],
	},
	pangde: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mengjin", "mashu"],
	},
	yanliangwenchou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["shuangxiong"],
	},
	yuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["luanji", "xueyi"],
		isZhugong: true,
	},
	xuhuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["duanliang"],
	},
	caopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xingshang", "fangzhu", "songwei"],
		isZhugong: true,
	},
	sunjian: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["yinghun"],
	},
	dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 8,
		skills: ["jiuchi", "roulin", "benghuai", "baonue"],
		isZhugong: true,
	},
	zhurong: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["juxiang", "lieren"],
	},
	menghuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["huoshou", "zaiqi"],
	},
	jiaxu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["wansha", "weimu", "luanwu"],
	},
	lusu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["haoshi", "dimeng"],
	},
	zhanghe: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qiaobian"],
	},
	dengai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["tuntian", "zaoxian"],
	},
	jiangwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["tiaoxin", "zhiji"],
	},
	liushan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xiangle", "fangquan", "ruoyu"],
		isZhugong: true,
	},
	sunce: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jiang", "hunzi", "zhiba"],
		isZhugong: true,
	},
	zhangzhaozhanghong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["zhijian", "guzheng"],
	},
	zuoci: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xinsheng", "huashen"],
	},
	caiwenji: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["beige", "duanchang"],
	},

	wangji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["qizhi", "jinqu"],
	},
	yanyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["nzry_juzhan"],
	},
	wangping: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["nzry_feijun", "nzry_binglve"],
	},
	luji: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["nzry_huaiju", "nzry_yili", "nzry_zhenglun"],
		clans: ["吴郡陆氏"],
	},
	sunliang: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["nzry_kuizhu", "nzry_zhizheng", "nzry_lijun"],
		isZhugong: true,
	},
	xuyou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nzry_chenglve", "nzry_shicai", "nzry_cunmu"],
	},
	yl_luzhi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nzry_mingren", "nzry_zhenliang"],
	},
	kuailiangkuaiyue: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["nzry_jianxiang", "nzry_shenshi"],
		names: "蒯|良-蒯|越",
	},

	guanqiujian: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["zhengrong", "hongju"],
		names: "毌丘|俭",
	},
	haozhao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["drlt_zhengu"],
	},
	zhugezhan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xinfu_zuilun", "xinfu_fuyin"],
		names: "诸葛|瞻",
	},
	lukang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["drlt_qianjie", "drlt_jueyan", "drlt_poshi"],
		clans: ["吴郡陆氏"],
	},
	yl_yuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["drlt_yongsi", "drlt_weidi"],
		isZhugong: true,
	},
	zhangxiu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["drlt_xiongluan", "drlt_congjian", "twjuxiang"],
		isZhugong: true,
	},
	chendao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dcwanglie"],
	},
	zhoufei: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["olliangyin", "olkongsheng"],
		names: "周|null",
	},
};

export default characters;
