const characters = {
  ol_caoren: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["rejushou", "rejiewei"],
    dieAudios: ["re_caoren"],
  },
  ol_xiahouyuan: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reshensu", "shebian"],
    names: "夏侯|渊",
  },
  ol_huangzhong: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["olliegong"],
  },
  ol_weiyan: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rekuanggu", "reqimou"],
  },
  ol_xiaoqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["oltianxiang", "rehongyan", "piaoling"],
    names: "桥|null",
  },
  ol_zhoutai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["olbuqu", "refenji"],
    dieAudios: ["re_zhoutai"],
  },
  ol_zhangjiao: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["olleiji", "reguidao", "rehuangtian"],
    isZhugong: true,
  },
  ol_yuji: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["olguhuo"],
  },
  ol_shen_guanyu: {
    sex: "male",
    group: "shen",
    hp: 5,
    skills: ["rewushen", "wuhun"],
    groupInGuozhan: "shu",
    dieAudios: ["shen_guanyu"],
  },
  ol_shen_lvmeng: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["shelie", "gongxin"],
    groupInGuozhan: "wu",
  },
  ol_dianwei: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["olqiangxi", "ninge"],
  },
  ol_xunyu: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["quhu", "oljieming"],
    clans: ["颍川荀氏"],
  },
  ol_sp_zhugeliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["bazhen", "olhuoji", "olkanpo", "cangzhuo"],
    names: "诸葛|亮",
  },
  ol_pangtong: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["ollianhuan", "olniepan"],
  },
  ol_taishici: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["tianyi", "hanzhan"],
    names: "太史|慈",
  },
  ol_pangde: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["mashu", "rejianchu"],
  },
  ol_yuanshao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["olluanji", "rexueyi"],
    isZhugong: true,
  },
  ol_yanwen: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["olshuangxiong"],
    names: "颜|良-文|丑",
  },
  ol_shen_zhouyu: {
    sex: "male",
    group: "shen",
    hp: 4,
    skills: ["qinyin", "yeyan"],
    groupInGuozhan: "wu",
  },
  ol_shen_zhugeliang: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["qixing", "kuangfeng", "dawu"],
    groupInGuozhan: "shu",
    names: "诸葛|亮",
  },
  ol_caopi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["rexingshang", "refangzhu", "songwei"],
    isZhugong: true,
  },
  ol_xuhuang: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["olduanliang", "rejiezi"],
  },
  ol_zhurong: {
    sex: "female",
    group: "shu",
    hp: 4,
    skills: ["juxiang", "lieren", "changbiao"],
    names: "null|null",
  },
  ol_menghuo: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["huoshou", "olzaiqi"],
  },
  ol_lusu: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["olhaoshi", "oldimeng"],
  },
  ol_sunjian: {
    sex: "male",
    group: "wu",
    hp: 4,
    maxHp: 5,
    skills: ["yinghun", "wulie"],
  },
  ol_dongzhuo: {
    sex: "male",
    group: "qun",
    hp: 8,
    skills: ["oljiuchi", "roulin", "benghuai", "olbaonue"],
    isZhugong: true,
  },
  ol_jiaxu: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["olweimu", "olwansha", "olluanwu"],
  },
  ol_shen_lvbu: {
    sex: "male",
    group: "shen",
    hp: 5,
    skills: ["kuangbao", "wumou", "wuqian", "shenfen"],
    groupInGuozhan: "qun",
    dieAudios: ["shen_lvbu"],
  },
  ol_shen_caocao: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["guixin", "feiying"],
    groupInGuozhan: "wei",
    dieAudios: ["shen_caocao"],
  },
  ol_dengai: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["oltuntian", "olzaoxian"],
  },
  ol_zhanghe: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["olqiaobian"],
  },
  ol_jiangwei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["oltiaoxin", "olzhiji"],
  },
  ol_liushan: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["xiangle", "olfangquan", "olruoyu"],
    isZhugong: true,
  },
  ol_sunce: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["oljiang", "olhunzi", "olzhiba"],
    isZhugong: true,
  },
  ol_zhangzhang: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["olzhijian", "olguzheng"],
    names: "张|昭-张|纮",
  },
  ol_zuoci: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["olhuashen", "olxinsheng"],
  },
  ol_caiwenji: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["olbeige", "duanchang"],
  },
  ol_shen_simayi: {
    sex: "male",
    group: "shen",
    hp: 4,
    skills: ["olrenjie", "olbaiyin", "lianpo"],
    groupInGuozhan: "wei",
    names: "司马|懿",
  },
  ol_shen_zhaoyun: {
    sex: "male",
    group: "shen",
    hp: 2,
    skills: ["rejuejing", "relonghun"],
    groupInGuozhan: "shu",
  },
}

export default characters
