export default {
  "#rejianxiong_ol_caocao1": "燕雀安知鸿鹄之志。",
  "#rejianxiong_ol_caocao2": "夫英雄者，胸怀大志，腹有良谋。",
  "#rehujia1": "护卫何在！",
  "#rehujia2": "大胆逆贼！谁可擒之？",
  "#ol_caocao:die": "华佗何在……",

  "#botu1": "今日起兵，渡江攻敌！",
  "#botu2": "时机已到，全军出击！",

  "#olyaowu1": "这些杂兵，我有何惧！",
  "#olyaowu2": "有吾在此，解太师烦忧。",
  "#shizhan1": "兀那汉子，且报上名来！",
  "#shizhan2": "看你能坚持几个回合！",
  "#ol_huaxiong:die": "我掉以轻心了……",

  "#reshensu_ol_xiahouyuan1": "奔轶绝尘，不留踪影。",
  "#reshensu_ol_xiahouyuan2": "健步如飞，破敌不备。",
  "#shebian1": "设变力战，虏敌千万。",
  "#shebian2": "随机应变，临机设变。",
  "#ol_xiahouyuan:die": "我的速度，还是不够……",

  "#olliegong1": "龙骨成镞，矢破苍穹。",
  "#olliegong2": "凤翎为羽，箭没坚城。",
  "#ol_huangzhong:die": "末将有负主公重托……",

  "#rekuanggu_ol_weiyan1": "只有战场，能让我感到兴奋。",
  "#rekuanggu_ol_weiyan2": "反骨狂傲，彰显本色！",
  "#reqimou1": "勇战不如奇谋。",
  "#reqimou2": "为了胜利，可以出其不意。",
  "#ol_weiyan:die": "奸贼害我……",

  "#oltianxiang1": "你岂会懂我的美丽？",
  "#oltianxiang2": "碧玉闺秀，只可远观。",
  "#rehongyan1": "我的容貌，让你心动了吗？",
  "#rehongyan2": "红颜娇花好，折花门前盼。",
  "#piaoling1": "清风拂君，落花飘零。",
  "#piaoling2": "花自飘零水自流。",
  "#ol_xiaoqiao:die": "同心而离居，忧伤以终老。",

  "#olleiji1": "疾雷迅电，不可趋避！",
  "#olleiji2": "雷霆之诛，灭军毁城！",
  "#reguidao1": "鬼道运行，由我把控！",
  "#reguidao2": "汝之命运，吾来改之！",
  "#rehuangtian1": "黄天法力，万军可灭！",
  "#rehuangtian2": "天书庇佑，黄巾可兴！",
  "#ol_zhangjiao:die": "天书无效，人心难聚……",

  "#olguhuo1": "这牌，猜对了吗？",
  "#olguhuo2": "真真假假，虚实难测。",
  "#rechanyuan1": "此咒甚重，怨念缠身。",
  "#rechanyuan2": "不信吾法，无福之缘。",
  "#ol_yuji:die": "符水失效，此病难医……",

  "#olqiangxi1": "典韦来也，谁敢一战！",
  "#olqiangxi2": "双戟青罡，百死无生。",
  "#ninge1": "古之恶来，今之典韦。",
  "#ninge2": "宁为刀俎，不为鱼肉。",
  "#ol_dianwei:die": "为将者，怎可徒手而亡？",

  "#quhu_ol_xunyu1": "两虎相斗，旁观成败。",
  "#quhu_ol_xunyu2": "驱兽相争，坐收渔利。",
  "#oljieming1": "含气在胸，有进无退。",
  "#oljieming2": "蕴节于形，生死无惧。",
  "#ol_xunyu:die": "一招不慎，为虎所噬……",

  "#bazhen_ol_sp_zhugeliang1": "八阵连心，日月同辉。",
  "#bazhen_ol_sp_zhugeliang2": "此阵变化，岂是汝等可解？",
  "#olhuoji1": "东风，让这火烧得再猛烈些吧！",
  "#olhuoji2": "赤壁借东风，燃火灭魏军。",
  "#olkanpo1": "此计奥妙，我已看破。",
  "#olkanpo2": "还有什么是我看不破的？",
  "#cangzhuo1": "藏巧于拙，用晦而明。",
  "#cangzhuo2": "寓清于浊，以屈为伸。",
  "#ol_sp_zhugeliang:die": "星途半废，夙愿未完。",

  "#ollianhuan1": "连环之策，攻敌之计。",
  "#ollianhuan2": "锁链连舟，困步难行。",
  "#olniepan1": "烈火脱胎，涅槃重生。",
  "#olniepan2": "破而后立，方有大成。",
  "#bazhen_ol_pangtong1": "八卦四象，阴阳运转。",
  "#bazhen_ol_pangtong2": "离火艮山，皆随我用。",
  "#olhuoji_ol_pangtong1": "火计诱敌，江水助势。",
  "#olhuoji_ol_pangtong2": "火烧赤壁，曹贼必败。",
  "#olkanpo_ol_pangtong1": "卧龙之才，吾也略懂。",
  "#olkanpo_ol_pangtong2": "这些小伎俩，逃不出我的眼睛！",
  "#ol_pangtong:die": "骥飞羽落，坡道归尘。",

  "#retianyi1": "天降大任，速战解围！",
  "#retianyi2": "义不从之，天必不佑！",
  "#hanzhan1": "伯符，且与我一战！",
  "#hanzhan2": "与君酣战，快哉快哉！",
  "#ol_taishici:die": "无妄之灾，难以避免……",

  "#rejianchu1": "你这身躯，怎么能快过我？",
  "#rejianchu2": "这些怎么能挡住我的威力！",
  "#ol_pangde:die": "人亡马倒，命之所归。",

  "#olluanji1": "我的箭支，准备颇多！",
  "#olluanji2": "谁都挡不住我的箭阵！",
  "#rexueyi1": "高贵名门，族裔盛名。",
  "#rexueyi2": "贵裔之脉，后起之秀！",
  "#ol_yuanshao:die": "孟德此计，防不胜防……",

  "#olshuangxiong1": "兄弟协力，定可于乱世纵横。",
  "#olshuangxiong2": "吾执矛，汝执槊，此天下可有挡我者。",
  "#ol_yanwen:die": "双雄皆陨，徒隆武圣之名……",

  "#olduanliang1": "焚其粮营，断其粮道。",
  "#olduanliang2": "兵行无常，计行断粮。",
  "#rejiezi1": "剪径截辎，惠泽同袍。",
  "#rejiezi2": "截敌粮草，以资袍泽。",
  "#ol_xuhuang:die": "亚夫易老，李广难封。",

  "#juxiang_ol_zhurong1": "南兵象阵，刀枪不入！",
  "#juxiang_ol_zhurong2": "巨象冲锋，踏平敌阵！",
  "#lieren_ol_zhurong1": "烈火飞刃，例无虚发！",
  "#lieren_ol_zhurong2": "烈刃一出，谁与争锋？",
  "#changbiao1": "长标如虹，以伐蜀汉！",
  "#changbiao2": "长标在此，谁敢拦我？",
  "#ol_zhurong:die": "这汉人，竟……如此厉害……",

  "#huoshou_ol_menghuo1": "坐据三山，蛮霸四野！",
  "#huoshou_ol_menghuo2": "啸据哀牢，闻祸而喜！",
  "#olzaiqi1": "挫而弥坚，战而弥勇！",
  "#olzaiqi2": "蛮人骨硬，其势复来！",
  "#ol_menghuo:die": "勿再放我，但求速死……",

  "#olhaoshi1": "仗义疏财，深得人心。",
  "#olhaoshi2": "招聚少年，给其衣食。",
  "#oldimeng1": "深知其奇，相与亲结。",
  "#oldimeng2": "同盟之人，言归于好。",
  "#ol_lusu:die": "一生为国，纵死无憾！",

  "#yinghun_ol_sunjian1": "提刀奔走，灭敌不休。",
  "#yinghun_ol_sunjian2": "贼寇草莽，我且出战。",
  "#wulie1": "孙武之后，英烈勇战。",
  "#wulie2": "兴义之中，忠烈之名。",
  "#ol_sunjian:die": "袁术之辈，不可共谋！",

  "#oljiuchi1": "好酒，痛快！",
  "#oljiuchi2": "某，千杯不醉！",
  "#roulin_ol_dongzhuo1": "醇酒美人，幸甚乐甚！",
  "#roulin_ol_dongzhuo2": "这些美人，都可进贡。",
  "#benghuai_ol_dongzhuo1": "何人伤我？",
  "#benghuai_ol_dongzhuo2": "酒色伤身呐……",
  "#olbaonue1": "天下群雄，唯我独尊！",
  "#olbaonue2": "吾乃人屠，当以兵为贡。",
  "#ol_dongzhuo:die": "地府可有美人乎？",

  "#olweimu1": "此伤与我无关。",
  "#olweimu2": "还是另寻他法吧。",
  "#olwansha1": "斩草务尽，以绝后患。",
  "#olwansha2": "有谁敢试试？",
  "#olluanwu1": "一切，都在我的掌控中。",
  "#olluanwu2": "这乱世还不够乱！",
  "#ol_jiaxu:die": "此劫……我已有所算……",

  "#oltuntian1": "垦田南山，志在西川。",
  "#oltuntian2": "兵农一体，以屯养战。",
  "#olzaoxian1": "良田厚土，足平蜀道之难。",
  "#olzaoxian2": "效仿五丁开川，赢粮直捣黄龙。",
  "#jixi_ol_dengai1": "明至剑阁，暗袭蜀都。",
  "#jixi_ol_dengai2": "良田为济，神兵天降。",
  "#ol_dengai:die": "钟会，你为何害我……",

  "#olqiaobian1": "顺势而变，则胜矣。",
  "#olqiaobian2": "万物变化，固无休息。",
  "#ol_zhanghe:die": "何处之流矢……",

  "#oltiaoxin1": "宜乘其衅会，以挑敌将。",
  "#oltiaoxin2": "会闻用师，观衅而动。",
  "#olzhiji1": "丞相遗志，不死不休！",
  "#olzhiji2": "大业未成，矢志不渝！",
  "#reguanxing_ol_jiangwei1": "星之分野，各有所属。",
  "#reguanxing_ol_jiangwei2": "星象相衔，此乃吉兆！",
  "#ol_jiangwei:die": "星散流离……",

  "#xiangle_ol_liushan1": "嘿嘿嘿，还是玩耍快乐~",
  "#xiangle_ol_liushan2": "美好的日子，应该好好享受。",
  "#olfangquan1": "蜀汉有相父在，我可安心。",
  "#olfangquan2": "这些事情，你们安排就好。",
  "#olruoyu1": "若愚故泰，巧骗众人。",
  "#olruoyu2": "愚昧者，非真傻也。",
  "#rejijiang_ol_liushan1": "爱卿爱卿，快来护驾！",
  "#rejijiang_ol_liushan2": "将军快替我，拦下此贼！",
  "#sishu1": "蜀乐乡土，怎不思念？",
  "#sishu2": "思乡心切，徘徊惶惶。",
  "#ol_liushan:die": "将军英勇，我……我投降……",

  "#oljiang1": "收合流散，东据吴会。",
  "#oljiang2": "策虽暗稚，窃有微志。",
  "#olhunzi1": "江东新秀，由此崛起。",
  "#olhunzi2": "看汝等大展英气！",
  "#olzhiba1": "让将军在此恭候多时了。",
  "#olzhiba2": "有诸位将军在，此战岂会不胜？",
  "#reyingzi_ol_sunce1": "得公瑾辅助，策必当一战！",
  "#reyingzi_ol_sunce2": "公瑾在此，此战无忧！",
  "#yinghun_ol_sunce1": "东吴繁盛，望父亲可知。",
  "#yinghun_ol_sunce2": "父亲，吾定不负你期望！",
  "#ol_sunce:die": "汝等，怎能受于吉蛊惑？",

  "#olzhijian1": "君有恙，臣者当舍命除之。",
  "#olzhijian2": "臣有言在喉，不吐不快。",
  "#olguzheng1": "兴国为任，可驱百里之行。",
  "#olguzheng2": "固政之责，在君亦在臣。",
  "#ol_zhangzhang:die": "老臣年迈，无力为继。",

  "#olhuashen1": "容貌发肤，不过浮尘。",
  "#olhuashen2": "皮囊万千，吾皆可化。",
  "#olxinsheng1": "枯木发荣，朽木逢春。",
  "#olxinsheng2": "风靡云涌，万丈光芒。",
  "#ol_zuoci:die": "红尘看破，驾鹤仙升。",

  "#olbeige1": "箜篌鸣九霄，闻者心俱伤。",
  "#olbeige2": " 琴弹十八拍，听此双泪流。",
  "#duanchang_ol_caiwenji1": "红颜留塞外，愁思欲断肠。",
  "#duanchang_ol_caiwenji2": "莫吟苦辛曲，此生谁忍闻。",
  "#ol_caiwenji:die": "飘飘外域里，何日能归乡？",
}
