const characters = {
  yuejin: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["xiaoguo"],
  },
  lidian: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["xunxun", "wangxi"],
  },
  sp_caiwenji: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["chenqing", "mozhi"],
  },
  caoang: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["kangkai"],
  },
  simalang: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["junbing", "quji"],
    names: "司马|朗",
  },
  guanyinping: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["xueji", "huxiao", "wuji"],
  },
  sp_sunshangxiang: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["liangzhu", "fanxiang"],
  },
  dongyun: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["bingzheng", "sheyan"],
  },
  sunqian: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["qianya", "shuimeng"],
  },
  dingfeng: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["duanbing", "fenxun"],
  },
  zhugejin: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["huanshi", "hongyuan", "mingzhe"],
    names: "诸葛|瑾",
    clans: ["琅琊诸葛氏"],
  },
  zhugeke: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["aocai", "duwu"],
    names: "诸葛|恪",
    clans: ["琅琊诸葛氏"],
  },
  sp_pangtong: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["guolun", "songsang"],
  },
  yanjun: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["guanchao", "xunxian"],
  },
  hetaihou: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["zhendu", "qiluan"],
    names: "何|null",
  },
  liuxie: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["tianming", "mizhao"],
  },
  sp_huangyueying: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["jiqiao", "linglong"],
  },
  tadun: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["luanzhan"],
    names: "null|null",
  },
  liuyao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["kannan"],
  },

  chenlin: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["bifa", "songci"],
  },
  zhugedan: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["gongao", "juyi"],
    names: "诸葛|诞",
    clans: ["琅琊诸葛氏"],
  },
  sp_jiangwei: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["kunfen", "fengliang"],
  },
  litong: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["tuifeng"],
  },
  zhuling: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["zhanyi"],
  },
  caochun: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["shanjia"],
  },
  tangzi: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["xingzhao"],
  },
  jiakui: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["zhongzuo", "wanlan"],
  },
  shamoke: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["jili"],
    names: "null|null",
  },
  zhangxingcai: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["shenxian", "qiangwu"],
  },
  maliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["zishu", "yingyuan"],
  },
  spzhangyi: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["zhiyi"],
  },
  lifeng: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["tunchu", "shuliang"],
  },
  dengzhi: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["jimeng", "shuaiyan"],
  },
  chenzhen: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["shameng"],
  },
  sunluyu: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["meibu", "mumu"],
  },
  buzhi: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["hongde", "dingpan"],
  },
  lvdai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["qinguo"],
  },
  zhoufang: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["duanfa", "youdi"],
  },
  sunru: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["yingjian", "shixin"],
  },
  lingcao: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["dujin"],
  },
  sufei: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["lianpian"],
  },
  panfeng: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["kuangfu"],
  },
  ol_hetaihou: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["olzhendu", "olqiluan"],
    names: "何|null",
    dieAudios: ["hetaihou"],
  },
  fuwan: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["moukui"],
  },
  sp_machao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["zhuiji", "shichou"],
  },
  zhanglu: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["yishe", "bushi", "midao"],
  },
  liuqi: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["wenji", "tunjiang"],
  },
  lisu: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["qiaoyan", "xianzhu"],
  },
  dongcheng: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["chengzhao"],
  },
  liangxing: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["lulve", "zhuixi"],
  },

  ol_zhangchunhua: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["jueqing", "shangshi", "jianmie"],
  },
  re_zhangxingcai: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["reshenxian", "qiangwu"],
    dieAudios: ["zhangxingcai"],
  },

  // ol_xuelingyun: {
  //   sex: "female",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["siqi", "qiaozhi"],
  // },
  // xiahouxuan: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["huanfu", "qingyi", "zeyue"],
  // },
  // yanrou: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["choutao", "xiangshu"],
  // },
  // qinghegongzhu: {
  //   sex: "female",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["zengou", "zhangji"],
  // },
  // caofang: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["zhimin", "dcjujian"],
  //   isZhugong: true,
  // },
  // duyu: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["jianguo", "qingshi"],
  //   groupBorder: "jin",
  // },
  // huanfan: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["sp_jianzheng", "fumou"],
  // },
  // zhenghun: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["dcqiangzhi", "pitian"],
  // },
  // zhaoyan: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["funing", "bingji"],
  // },
  // wenqin: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["guangao", "huiqi"],
  // },
  // jx_zhonghui: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["jx_quanji", "zili"],
  // },
  // yanghuiyu: {
  //   sex: "female",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["hongyi", "quanfeng"],
  //   groupBorder: "jin",
  // },
  // xizhicai: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["tiandu", "xianfu", "chouce"],
  // },
  // jx_zhangchunhua: {
  //   sex: "female",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["jueqing", "shangshi", "jianmie"],
  // },
  // wangyuanji: {
  //   sex: "female",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["qianchong", "shangjian"],
  //   groupBorder: "jin",
  // },
  // caoying: {
  //   sex: "female",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["lingren", "fujian"],
  // },
  // caochun: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["shanjia"],
  // },
  // zhaoang: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 3,
  //   maxHp: 4,
  //   skills: ["zhongjie", "sushou"],
  // },
  // jx_manchong: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["jx_junxing", "yuce"],
  // },
  // bianyue: {
  //   sex: "female",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["bizu", "jwuxie"],
  // },
  // chengjichengcui: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 6,
  //   skills: ["tousui", "chuming"],
  //   groupBorder: "jin",
  // },
  // qianzhao: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["weifu", "kuansai"],
  // },
  // huban: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["huiyun"],
  // },
  // bianxi: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["dunxi"],
  // },
  // jiangwan: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["ziruo", "xvfa"],
  // },
  // feiyi: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["yanru", "hezhong"],
  // },
  // pengyang: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["xiaofan", "tuishi", "cunmu"],
  // },
  // mengda: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["goude"],
  // },
  // zhangyi: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["zhiyi"],
  // },
  // chenshi: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["qingbei"],
  // },
  // yangyi: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["dingcuo", "juanxia"],
  // },
  // huangwudie: {
  //   sex: "female",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["shuangrui", "fuxie"],
  // },
  // wolongfengchu: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["youlong", "luanfeng"],
  // },
  // md_guanping: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["wuwei"],
  // },
  // panghong: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["pingzhi", "gangjian"],
  // },
  // dengzhi: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["jianliang", "weimeng"],
  // },
  // hujinding: {
  //   sex: "female",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["qingyuan", "chongshen"],
  // },
  // wuban: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["youzhan"],
  // },
  // qinmi: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["zhuandui", "jianzheng", "tianbian"],
  // },
  // jx_wuyi: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["jx_benxi"],
  // },
  // re_zhangsong: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["qiangzhi", "rexiantu"],
  // },
  // zhangxingcai: {
  //   sex: "female",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["oldshenxian", "qiangwu"],
  //   dieAudios: ["zhangxingcai"],
  // },
  // dc_huojun: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["dcgue", "dcsigong"],
  // },
  // ol_zhouqun: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["oltianhou", "olchenshuo"],
  // },
  // mb_ganfuren: {
  //   sex: "female",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["mbzhijie", "mbshushen"],
  // },
  // re_liuchen: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["rezhanjue", "reqinwang"],
  //   isZhugong: true,
  // },
  // qiaozhou: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["zhiming", "xingbu"],
  // },
  // wuke: {
  //   sex: "female",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["mbanda", "mbzhuguo"],
  //   names: "吴|null",
  // },
  // zhangbu: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["mbchengxiong", "mbwangzhuang"],
  // },
  // dc_sunchen: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 4,
  //   skills: ["dczigu", "dczuowei"],
  // },
  // re_xusheng: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 4,
  //   skills: ["repojun"],
  // },
  // re_zhuran: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 4,
  //   skills: ["xindanshou"],
  // },
  // zhugejin: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["huanshi", "olhongyuan", "olmingzhe"],
  //   names: "诸葛|瑾",
  // },
  // sunhao: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 5,
  //   skills: ["recanshi", "rechouhai", "guiming"],
  //   isZhugong: true,
  // },
  // ol_lukai: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["olxuanzhu", "oljiane"],
  // },
  // ol_sunru: {
  //   sex: "female",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["olchishi", "olweimian"],
  // },
  // tengyin: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["chenjian", "xixiu"],
  // },
  // re_liuzan: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 4,
  //   skills: ["refenyin", "liji"],
  // },
  // dc_luotong: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["renzheng", "jinjian"],
  // },
  // dc_tengfanglan: {
  //   sex: "female",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["dcluochong", "dcaichen"],
  // },
  // dc_lingcao: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 4,
  //   maxHp: 5,
  //   skills: ["dcdufeng"],
  // },
  // zhangwen: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["songshu", "sibian"],
  // },
  // quhuang: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["olqiejian", "olnishou"],
  // },
  // ol_luyusheng: {
  //   sex: "female",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["olcangxin", "olrunwei"],
  // },
  // panshu: {
  //   sex: "female",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["weiyi", "jinzhi"],
  // },
  // panjun: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["xinfu_guanwei", "xinfu_gongqing"],
  // },
  // sb_huanggai: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 4,
  //   skills: ["sbkurou", "sbzhaxiang"],
  // },
  // sb_handang: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 4,
  //   skills: ["sbgongqi", "sbjiefan"],
  // },
  // re_bulianshi: {
  //   sex: "female",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["reanxu", "zhuiyi"],
  // },

  // v_sunquan: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 4,
  //   skills: ["dcwoheng", "dcyuhui"],
  // },
  // sb_luxun: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["sbqianxun", "sblianying"],
  // },
  // zerong: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["dccansi", "dcfozong"],
  // },
  // ol_hanfu: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["olshuzi", "olkuangshou"],
  // },
  // liubian: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 3,
  //   skills: ["shiyuan", "dushi", "yuwei"],
  //   isZhugong: true,
  // },
  // xin_jushou: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 2,
  //   maxHp: 3,
  //   hujia: 3,
  //   skills: ["xinjianying", "shibei"],
  // },
  // yj_xuhuang: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["xinxhzhiyan"],
  // },
  // new_yj_dongzhuo: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 3,
  //   maxHp: 5,
  //   skills: ["xiongjin", "zhenbian", "baoxi"],
  // },
  // baoxin: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["mutao", "yimou"],
  //   dieAudios: ["tw_baoxin"],
  // },
  // sp_zhenji: {
  //   sex: "female",
  //   group: "qun",
  //   hp: 3,
  //   skills: ["dcjijie", "dchuiji"],
  // },
  // lvlingqi: {
  //   sex: "female",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["guowu", "zhuangrong"],
  // },
  // yj_huangzhong: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["spshidi", "spyishi", "spqishe"],
  // },
  // ol_liru: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 3,
  //   skills: ["oljuece", "olmieji", "dcfencheng"],
  // },
  // ol_liupi: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["olyicheng"],
  // },
  // lushi: {
  //   sex: "female",
  //   group: "qun",
  //   hp: 3,
  //   skills: ["olzhuyan", "olleijie"],
  //   names: "卢|null",
  // },
  // ol_sb_wenchou: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["olsblunzhan", "olsbjuejue"],
  // },
  // sp_ol_zhanghe: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["spolzhouxuan"],
  // },
  // ol_taoqian: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 3,
  //   skills: ["olzongluan", "olwenren", "olzhaohuo"],
  // },
  // liuyan: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 3,
  //   skills: ["xinfu_tushe", "xinfu_limu"],
  // },
  // weizi: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 3,
  //   skills: ["yuanzi", "liejie"],
  // },
  // tianchou: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["olshandao"],
  // },
  // sp_menghuo: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["spmanwang"],
  // },
  // yj_ganning: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["gnjinfan", "gnsheque"],
  // },
  // yj_zhanghuan: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["dcyiju", "dcshuguo"],
  // },
  // yj_weiyan: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   maxHp: 4,
  //   hujia: 1,
  //   skills: ["mbguli", "mbaosi"],
  // },
  // sb_lvbu: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 5,
  //   skills: ["sbwushuang", "sbliyu"],
  // },
  // yanfuren: {
  //   sex: "female",
  //   group: "qun",
  //   hp: 3,
  //   skills: ["channi", "nifu"],
  // },
}

export default characters
