const characters = {
  ol_caocao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["rejianxiong", "rehujia"],
    isZhugong: true,
  },
  ol_simayi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["refankui", "reguicai"],
    names: "司马|懿",
    dieAudios: ["re_simayi"],
  },
  ol_xiahoudun: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["olganglie", "qingjian"],
    names: "夏侯|惇",
    dieAudios: ["re_xiahoudun"],
  },
  ol_zhangliao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["retuxi"],
    dieAudios: ["re_zhangliao"],
  },
  ol_xuzhu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["olluoyi"],
    dieAudios: ["re_xuzhu"],
  },
  ol_guojia: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["tiandu", "reyiji"],
    dieAudios: ["re_guojia"],
  },
  ol_zhenji: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["reluoshen", "qingguo"],
    dieAudios: ["re_zhenji"],
  },
  ol_liubei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rerende", "rejijiang"],
    isZhugong: true,
    dieAudios: ["re_liubei"],
  },
  ol_guanyu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rewusheng", "yijue"],
    dieAudios: ["re_guanyu"],
  },
  ol_zhangfei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["olpaoxiao", "retishen"],
    dieAudios: ["re_zhangfei"],
  },
  ol_zhugeliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["reguanxing", "kongcheng"],
    names: "诸葛|亮",
    dieAudios: ["re_zhugeliang"],
  },
  ol_zhaoyun: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["relongdan", "reyajiao"],
    dieAudios: ["re_zhaoyun"],
  },
  ol_machao: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["mashu", "retieji"],
    dieAudios: ["re_machao"],
  },
  ol_huangyueying: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["oljizhi", "reqicai"],
    dieAudios: ["re_huangyueying"],
  },
  ol_sunquan: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["rezhiheng", "oljiuyuan"],
    isZhugong: true,
    dieAudios: ["re_sunquan"],
  },
  ol_ganning: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["qixi", "fenwei"],
    dieAudios: ["re_ganning"],
  },
  ol_lvmeng: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["keji", "reqinxue", "botu"],
    dieAudios: ["re_lvmeng"],
  },
  ol_huanggai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["rekurou", "rezhaxiang"],
    dieAudios: ["re_huanggai"],
  },
  ol_zhouyu: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["reyingzi", "refanjian"],
    dieAudios: ["re_zhouyu"],
  },
  ol_daqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["reguose", "liuli"],
    names: "桥|null",
    dieAudios: ["re_daqiao"],
  },
  ol_luxun: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["reqianxun", "relianying"],
    clans: ["吴郡陆氏"],
    dieAudios: ["re_luxun"],
  },
  ol_sunshangxiang: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["rejieyin", "xiaoji"],
    dieAudios: ["re_sunshangxiang"],
  },
  ol_huatuo: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jijiu", "chuli"],
    dieAudios: ["re_huatuo"],
  },
  ol_lvbu: {
    sex: "male",
    group: "qun",
    hp: 5,
    skills: ["wushuang", "liyu"],
    dieAudios: ["re_lvbu"],
  },
  ol_diaochan: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["relijian", "rebiyue"],
    names: "null|null",
    dieAudios: ["diaochan"],
  },
  ol_huaxiong: {
    sex: "male",
    group: "qun",
    hp: 6,
    skills: ["olyaowu", "shizhan"],
  },
  ol_gongsunzan: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["reyicong", "reqiaomeng"],
    dieAudios: ["re_gongsunzan"],
  },
}

export default characters
