const characters = {
  old_liubei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["oldrende", "jijiang"],
    isZhugong: true,
    dieAudios: ["liubei"],
  },
  old_huangyueying: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["oldjizhi", "oldqicai"],
    dieAudios: ["huangyueying"],
  },
  old_diaochan: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["relijian", "biyue"],
    names: "null|null",
  },
  old_yuanshu: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["wangzun", "tongji"],
  },

  old_caocao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["oldjianxiong", "hujia"],
    isZhugong: true,
    img: "image/character/re_caocao.jpg",
    dieAudios: ["ol_caocao"],
  },
  old_xiahoudun: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reganglie", "oldqingjian"],
    names: "夏侯|惇",
    img: "image/character/re_xiahoudun.jpg",
    dieAudios: ["re_xiahoudun"],
  },
  old_zhangliao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["oldtuxi"],
    img: "image/character/re_zhangliao.jpg",
    dieAudios: ["re_zhangliao"],
  },
  old_xuzhu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["oldluoyi"],
    img: "image/character/re_xuzhu.jpg",
    dieAudios: ["re_xuzhu"],
  },
  old_guojia: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["tiandu", "oldyiji"],
    img: "image/character/re_guojia.jpg",
    dieAudios: ["re_guojia"],
  },
  old_guanyu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["wusheng", "oldyijue"],
    img: "image/character/re_guanyu.jpg",
    dieAudios: ["re_guanyu"],
  },
  old_zhangfei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["paoxiao", "oldtishen"],
    img: "image/character/re_zhangfei.jpg",
    dieAudios: ["re_zhangfei"],
  },
  old_zhaoyun: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["longdan", "oldyajiao"],
    img: "image/character/re_zhaoyun.jpg",
    dieAudios: ["re_zhaoyun"],
  },
  re_xushu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["zhuhai", "qianxin"],
  },
  old_lvbu: {
    sex: "male",
    group: "qun",
    hp: 5,
    skills: ["wushuang", "oldliyu"],
    img: "image/character/re_lvbu.jpg",
    dieAudios: ["re_lvbu"],
  },

  old_yujin: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["yizhong"],
  },
  old_fazheng: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["oldenyuan", "oldxuanhuo"],
  },
  old_masu: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["xinzhan", "huilei"],
    dieAudios: ["masu"],
  },
  old_xushu: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["oldwuyan", "oldjujian"],
    groupBorder: "wei",
  },
  old_lingtong: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["oldxuanfeng"],
    dieAudios: ["lingtong"],
  },
  old_xusheng: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["oldpojun"],
    img: "image/character/dc_xusheng.jpg",
    dieAudios: ["xusheng"],
  },

  old_caozhang: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["oldjiangchi"],
    dieAudios: ["caozhang"],
  },
  old_wangyi: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["oldzhenlie", "oldmiji"],
  },
  old_guanzhang: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["oldfuhun"],
    names: "关|兴-张|苞",
  },
  old_liaohua: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["olddangxian", "oldfuli"],
    dieAudios: ["liaohua"],
  },
  old_madai: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["mashu", "oldqianxi"],
  },
  old_handang: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["oldgongqi", "oldjiefan"],
    dieAudios: ["handang"],
  },
  old_huaxiong: {
    sex: "male",
    group: "qun",
    hp: 6,
    skills: ["shiyong"],
    dieAudios: ["re_huaxiong"],
  },
  old_liubiao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["oldzishou", "zongshi"],
    dieAudios: ["liubiao"],
  },

  old_caochong: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["oldchengxiang", "oldrenxin"],
    dieAudios: ["caochong"],
  },
  old_guohuai: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["oldjingce"],
    dieAudios: ["guohuai"],
  },
  old_manchong: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["oldjunxing", "yuce"],
    dieAudios: ["manchong"],
  },
  old_zhuran: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["olddanshou"],
    dieAudios: ["zhuran"],
  },
  old_fuhuanghou: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["oldzhuikong", "oldqiuyuan"],
    dieAudios: ["fuhuanghou"],
  },
  old_liru: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["oldjuece", "oldmieji", "oldfencheng"],
    dieAudios: ["liru"],
  },

  old_caozhen: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["oldsidi"],
    dieAudios: ["caozhen"],
  },
  old_chenqun: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["dingpin", "oldfaen"],
    dieAudios: ["chenqun"],
    clans: ["颍川陈氏"],
  },
  old_wuyi: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["oldbenxi"],
    dieAudios: ["wuyi"],
    clans: ["陈留吴氏"],
  },
  old_zhoucang: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["oldzhongyong"],
    dieAudios: ["zhoucang"],
  },
  old_zhuhuan: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["oldyoudi"],
  },

  old_caorui: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["huituo", "oldmingjian", "xingshuai"],
    isZhugong: true,
    dieAudios: ["caorui"],
  },
  old_caoxiu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["taoxi"],
    dieAudios: ["caoxiu"],
  },
  old_quancong: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["zhenshan"],
    dieAudios: ["quancong"],
  },

  old_huanghao: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["oldqinqing", "oldhuisheng"],
    img: "image/character/huanghao.jpg",
    dieAudios: ["huanghao"],
  },
  old_liuyu: {
    sex: "male",
    group: "qun",
    hp: 2,
    skills: ["oldzhige", "oldzongzuo"],
    dieAudios: ["liuyu"],
  },
  old_zhangrang: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["oldtaoluan"],
    trashBin: ["sex:male_castrated"],
    dieAudios: ["zhangrang"],
  },

  old_xinxianying: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["oldzhongjian", "oldcaishi"],
  },
  old_jikang: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["oldqingxian", "oldjuexiang"],
    dieAudios: ["jikang"],
  },

  yangxiu: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["danlao", "jilei"],
    clans: ["弘农杨氏"],
  },
  sp_yuanshu: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["spyongsi", "spweidi"],
  },
  old_sunshangxiang: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["jieyin", "xiaoji"],
    dieAudios: ["sunshangxiang"],
  },
  old_pangde: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["mashu", "mengjin"],
    dieAudios: ["pangde"],
  },
  sp_guanyu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["wusheng", "danji"],
    dieAudios: ["guanyu"],
  },
  old_caiwenji: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["beige", "duanchang"],
    dieAudios: ["caiwenji"],
  },
  old_machao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["mashu", "tieji"],
    dieAudios: ["machao"],
  },
  old_jiaxu: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["wansha", "luanwu", "weimu"],
    dieAudios: ["jiaxu"],
  },
  caohong: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["yuanhu"],
  },
  old_guanyinping: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["oldxueji", "oldhuxiao", "oldwuji"],
    dieAudios: ["guanyinping"],
  },
  old_lingju: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["jieyuan", "oldfenxin"],
    names: "吕|null",
    dieAudios: ["lingju"],
  },
  xiahouba: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["baobian"],
    names: "夏侯|霸",
  },
  daxiaoqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["xingwu", "luoyan"],
    names: "桥|null-桥|null",
  },
  sp_xiahoushi: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["spyanyu", "xiaode"],
    names: "夏侯|null",
    dieAudios: ["xiahoushi"],
  },
  zhangbao: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["zhoufu", "yingbing"],
  },
  old_panfeng: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["oldkuangfu"],
    dieAudios: ["panfeng"],
  },
  zumao: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["yinbing", "juedi"],
  },
  old_zhugedan: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["gongao", "oldjuyi"],
    names: "诸葛|诞",
    clans: ["琅琊诸葛氏"],
    dieAudios: ["zhugedan"],
  },
  old_sunluyu: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["oldmeibu", "oldmumu"],
    dieAudios: ["sunluyu"],
  },
  old_maliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["xiemu", "naman"],
  },
  zhangliang: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["jijun", "fangtong"],
  },
  old_ganfuren: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["oldshushen", "oldshenzhi"],
    names: "甘|null",
    dieAudios: ["ganfuren"],
  },
  huangjinleishi: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["fulu", "zhuji"],
    names: "null|null-null|null",
  },
  wenpin: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["zhenwei"],
  },
}

export default characters
