export default {
  old_diaochan: "绝世的舞姬",

  old_liubei: "乱世的枭雄",
  old_huangyueying: "归隐的杰女",
  old_yuanshu: "野心渐增",

  old_guanyu: "美髯公",
  old_zhangfei: "万夫不当",
  old_zhaoyun: "虎威将军",
  re_xushu: "化剑为犁",

  old_caocao: "魏武帝",
  old_xiahoudun: "独眼的罗刹",
  old_zhangliao: "前将军",
  old_xuzhu: "虎痴",
  old_guojia: "早终的先知",

  old_lvbu: "武的化身",

  old_yujin: "魏武之刚",
  old_fazheng: "蜀汉的辅翼",
  old_masu: "怀才自负",
  old_xushu: "忠孝的侠士",
  old_lingtong: "豪情烈胆",
  old_xusheng: "江东的铁壁",

  old_caozhang: "黄须儿",
  old_wangyi: "决意的巾帼",
  old_guanzhang: "将门虎子",
  old_liaohua: "历尽沧桑",
  old_madai: "临危受命",
  old_handang: "石城侯",
  old_huaxiong: "魔将",
  old_liubiao: "跨蹈汉南",

  old_caochong: "仁爱的神童",
  old_guohuai: "垂问秦雍",
  old_manchong: "政法兵谋",
  old_zhuran: "不动之督",
  old_fuhuanghou: "孤注一掷",
  old_liru: "魔仕",

  old_caozhen: "荷国天督",
  old_chenqun: "万世臣表",
  old_wuyi: "建兴鞍辔",
  old_zhoucang: "披肝沥胆",
  old_zhuhuan: "中洲拒天人",

  old_caorui: "天姿的明君",
  old_caoxiu: "千里骐骥",
  old_quancong: "慕势耀族",

  old_huanghao: "便辟佞慧",
  old_liuyu: "甘棠永固",
  old_zhangrang: "窃幸绝禋",

  old_xinxianying: "名门智女",
  old_jikang: "峻峰孤松",

  yangxiu: "恃才放旷",
  sp_yuanshu: "仲家帝",
  old_sunshangxiang: "梦醉良缘",
  old_pangde: "抬榇之悟",
  sp_guanyu: "汉寿亭侯",
  old_caiwenji: "金璧之才",
  old_machao: "西凉的猛狮",
  old_jiaxu: "算无遗策",
  caohong: "福将",
  guanyinping: "武姬",
  old_lingju: "情随梦逝",
  xiahouba: "棘途壮志",
  daxiaoqiao: "江东之花",
  sp_xiahoushi: "疾冲之恋",
  zhangbao: "地公将军",
  old_panfeng: "联军上将",
  zumao: "碧血染赤帻",
  old_zhugedan: "薤露蒿里",
  old_sunluyu: "舍身饲虎",
  old_maliang: "白眉智士",
  zhangliang: "黄昏的斗蛾",
  old_ganfuren: "旧甘夫人",
  huangjinleishi: "雷祭之姝",
  wenpin: "坚城宿将",
}
