const characterSort = {
  old_standard: [
    "old_diaochan",

    "old_liubei",
    "old_huangyueying",
    "old_yuanshu",
  ],
  old_shenhua: [],
  old_refresh: [
    "old_guanyu",
    "old_zhangfei",
    "old_zhaoyun",
    "re_xushu",

    "old_caocao",
    "old_xiahoudun",
    "old_zhangliao",
    "old_xuzhu",
    "old_guojia",

    "old_lvbu",
  ],
  old_yijiang1: [
    "old_yujin",
    "old_fazheng",
    "old_masu",
    "old_xushu",
    "old_lingtong",
    "old_xusheng",
  ],
  old_yijiang2: [
    "old_caozhang",
    "old_wangyi",
    "old_guanzhang",
    "old_liaohua",
    "old_madai",
    "old_handang",
    "old_huaxiong",
    "old_liubiao",
  ],
  old_yijiang3: [
    "old_caochong",
    "old_guohuai",
    "old_manchong",
    "old_zhuran",
    "old_fuhuanghou",
    "old_liru",
  ],
  old_yijiang4: [
    "old_caozhen",
    "old_chenqun",
    "old_wuyi",
    "old_zhoucang",
    "old_zhuhuan",
  ],
  old_yijiang5: ["old_caorui", "old_caoxiu", "old_quancong"],
  old_yijiang6: ["old_huanghao", "old_liuyu", "old_zhangrang"],
  old_yijiang7: ["old_xinxianying", "old_jikang"],
  sp_default: [
    "yangxiu",
    "sp_yuanshu",
    "old_sunshangxiang",
    "old_pangde",
    "sp_guanyu",
    "old_caiwenji",
    "old_machao",
    "old_jiaxu",
    "caohong",
    "old_guanyinping",
    "old_lingju",
    "xiahouba",
    "daxiaoqiao",
    "sp_xiahoushi",
    "zhangbao",
    "old_panfeng",
    "zumao",
    "old_zhugedan",
    "old_sunluyu",
  ],
}

const characterSortTranslate = {
  old_standard: "标准版",
  old_shenhua: "神话再临",
  old_refresh: "界限突破",
  old_yijiang1: "一将成名2011",
  old_yijiang2: "一将成名2012",
  old_yijiang3: "一将成名2013",
  old_yijiang4: "一将成名2014",
  old_yijiang5: "一将成名2015",
  old_yijiang6: "原创之魂2016",
  old_yijiang7: "原创之魂2017",
  sp_default: "桌游志SP",
}

export { characterSort, characterSortTranslate }
