export default {
  "#lijian_old_diaochan1": "嗯哼~",
  "#lijian_old_diaochan2": "夫君，你要替妾身做主啊！",
  "#biyue_old_diaochan1": "失礼啦~",
  "#biyue_old_diaochan2": "羡慕吧~",
  "#old_diaochan:die": "父亲大人，对不起……",

  "#wangzun1": "真命天子，八方拜服。",
  "#wangzun2": "归顺于我，封爵赏地。",
  "#tongji1": "弑君之罪，当诛九族。",
  "#tongji2": "你，你这是反啦。",
  "#old_yuanshu:die": "把玉玺，还给我……",

  "#zhuhai1": "早知今日，何必当初！",
  "#zhuhai2": "善恶有报，天道轮回！",
  "#qianxin1": "弃武从文，安邦卫国！",
  "#qianxin2": "既遇明主，天下可图！",
  "#jianyan1": "如此如此，敌军自破！",
  "#jianyan2": "开言纳谏，社稷之福！",
  "#re_xushu:die": "母亲……孩儿……尽孝来了。",

  "#yizhong1": "不先为备，何以待敌？",
  "#yizhong2": "稳重行军，百战不殆！",
  "#old_yujin:die": "我，无颜面对丞相了……",

  "#oldenyuan1": "滴水之恩，涌泉以报。",
  "#oldenyuan2": "得人恩果千年记。",
  "#oldenyuan3": "睚眦之怨，无不报复。",
  "#oldenyuan4": "谁敢得罪我？",
  "#oldxuanhuo1": "给你的，十倍奉还给我。",
  "#oldxuanhuo2": "重用许靖，以眩远近。",
  "#old_fazheng:die": "蜀翼既折，蜀汉哀矣……",

  "#xinzhan1": "吾通晓兵法，世人皆知。",
  "#xinzhan2": "用兵之道，攻心为上。",
  "#huilei1": "丞相视某如子，某以丞相为父。",
  "#huilei2": "谡愿以死安大局。",

  "#oldwuyan1": "嘘，言多必失啊。",
  "#oldwuyan2": "唉，一切尽在不言中。",
  "#oldjujian1": "我看好你！",
  "#oldjujian2": "将军岂愿抓牌乎？",
  "#old_xushu:die": "娘……孩儿不孝……向您……请罪……",

  "#oldzhenlie1": "我，绝不屈服！",
  "#oldzhenlie2": "休要小看妇人志气！",
  "#oldmiji1": "奇谋，只在绝境中诞生！",
  "#oldmiji2": "我将尽我所能！",
  "#old_wangyi:die": "忠义已尽，死又何妨？",

  "#oldfuhun1": "不血父仇，誓不罢休！",
  "#oldfuhun2": "承父遗志，横扫叛贼！",
  "#wusheng_old_guanzhang1": "蜀汉重任，后继有人！",
  "#paoxiao_old_guanzhang1": "哼！",
  "#old_guanzhang:die": "吾得父亲之遗志，未袭父亲之神勇。",

  "#oldqianxi1": "斩草除根，除恶务尽！",
  "#oldqianxi2": "伤其十指，不如断其一指！",
  "#old_madai:die": "反骨贼已除，丞相放心……",

  "#shiyong1": "好大一股酒气啊！",
  "#shiyong2": "好大一股杀气啊！",

  "#oldyoudi1": "无名小卒，可敢再前进一步！",
  "#oldyoudi2": "予以小利，必有大获。",
  "#old_zhuhuan:die": "这巍巍巨城，吾竟无力撼动。",

  "#oldzhongjian1": "行路八千里，方可辨忠奸。",
  "#oldzhongjian2": "观其行，明其志，而后知心。",
  "#oldcaishi1": "为谋大计，失小利亦无妨。",
  "#oldcaishi2": "才思敏捷，方可识人喻事。",
  "#old_xinxianying:die": "慧眼，也难看清这乱世的尘埃。",

  "#juexiang_ji1": "一弹一拨，铿锵有力！",
  "#juexiang_lie1": "一壶烈云烧，一曲人皆醉。",
  "#juexiang_rou1": "君子以琴会友，以瑟辅人。",
  "#juexiang_he1": "悠悠琴音，人人自醉。",

  "#danlao1": "我喜欢！",
  "#danlao2": "来来，一人一口！",
  "#jilei1": "曹公之意，我已了然！",
  "#jilei2": "食之无肉，弃之有味。",
  "#yangxiu:die": "我固自以死之晚也……",

  "#spyongsi1": "玉玺在手，天下我有。",
  "#spyongsi2": "大汉天下，已半入我手。",
  "#spweidi1": "你们都得听我的号令！",
  "#spweidi2": "我才是皇帝！",
  "#sp_yuanshu:die": "可恶！就差……一步了……",

  "#yuanhu1": "将军，这件兵器可还趁手？",
  "#yuanhu2": "刀剑无眼，须得小心防护。",
  "#yuanhu3": "宝马配英雄！哈哈哈哈…",
  "#caohong:die": "福兮祸所伏……",

  "#baobian1": "变可生，不变则死。",
  "#baobian2": "适时而动，穷极则变。",
  "#tiaoxin_xiahouba1": "黄口小儿，可听过将军名号?",
  "#tiaoxin_xiahouba2": "跪下受降，饶你不死！",
  "#paoxiao_xiahouba1": "受死吧！",
  "#paoxiao_xiahouba2": "喝！",
  "#shensu_xiahouba1": "今日有恙在身，须得速战速决！",
  "#shensu_xiahouba2": "冲杀敌阵，来去如电！",
  "#xiahouba:die": "弃魏投蜀，死而无憾。",

  "#xingwu1": "哼，不要小瞧女孩子哦！",
  "#xingwu2": "姐妹齐心，其利断金。",
  "#tianxiang_daxiaoqiao1": "哼，我才不怕你呢~",
  "#tianxiang_daxiaoqiao2": "替我挡着吧~",
  "#liuli_daxiaoqiao1": "不懂得怜香惜玉么~",
  "#liuli_daxiaoqiao2": "呵呵，交给你啦~",
  "#daxiaoqiao:die": "伯符，公瑾，请一定要守住我们的江东啊！",

  "#zhoufu1": "违吾咒者，倾死灭亡。",
  "#zhoufu2": "咒宝符命，速显威灵。",
  "#yingbing1": "朱雀玄武，誓为我征。",
  "#yingbing2": "所呼立至，所召立前。",
  "#zhangbao:die": "黄天，为何……",

  "#yinbing1": "追兵凶猛，末将断后！",
  "#yinbing2": "将军走此小道，追兵交我应付！",
  "#juedi1": "困兽之斗，以全忠义！",
  "#juedi2": "提起武器，最后一搏！",
  "#zumao:die": "孙将军，已经，安全了吧……",
}
