window.noname_package = {
	character: {
		//经典标包
		standard: "标准",
	},
	card: {
		standard: "标准",
	},
	mode: {
		identity: "身份",
	},
	submode: {
		identity: {
			normal: "身份模式",
		},
	},
	background: {
		ol_bg: "龙纹",
		planetarian_bg: "星梦",
		heaven_bg: "红烧",
		kyoani_bg: "京都",
		key_bg: "键社",
		xiaowu_bg: "小无",
		noname_bg: "璀璨",
		wuming_bg: "无名",
		zhulin_bg: "竹林",
		shengshi_bg: "盛世",
		taoyuan_bg: "桃园",
		zhanhuo_bg: "战火",
		huangtian_bg: "黄天",
		september_bg: "九月",
		yinxiang_bg: "印象",
		zhanyun_bg: "战云",
		beipan_bg: "背叛",
		lanting_bg: "兰亭",
		lingju_bg: "灵雎",
		sanying_bg: "三英",
		wangshi_bg: "往事",
		xiongxin_bg: "雄心",
		xinsha_bg: "新杀",
	},
	music: {
		music_phliosophy: "Philosophy of ours",
		music_diaochan: "貂蝉",
		music_shezhan: "舌战群儒",
		music_danji: "千里走单骑",
		music_jifeng: "祭风",
		music_jilve: "极略",
		effect_caomaoBJM: "向死存魏",
		effect_yinzhanBGM: "势魏延饮战",
		effect_tuishouBGM: "势魏延退守",
	},
	font: {
		xiaozhuan: "方正小篆体",
		xinwei: "华文新魏_GBK",
		huangcao: "方正黄草_GBK",
		yuanli: "方正北魏楷书_GBK",
		xingkai: "方正行楷_GBK",
		shousha: "方正隶变_GBK",
	},
	theme: {
		woodden: "木纹",
		music: "音乐",
		simple: "简约",
	},
};
