const characterSort = {
  shiji_zhi: [
    "bianfuren",
    "sp_wangcan",
    "feiyi",
    "re_chenzhen",
    "sp_sunshao",
    "luotong",
    "sp_xunchen",
    "sp_duyu",
    "shen_guojia",
    "shen_xunyu",
  ],
  shiji_xin: [
    "sp_xinpi",
    "wangling",
    "sp_mifuren",
    "wangfuzhaolei",
    "wujing",
    "zhouchu",
    "sp_kongrong",
    "sp_yanghu",
    "shen_taishici",
    "shen_sunce",
  ],
  shiji_ren: [
    "sp_huaxin",
    "caizhenji",
    "xiangchong",
    "sp_xujing",
    "sp_zhangwen",
    "qiaogong",
    "zhangzhongjing",
    "liuzhang",
    "shen_huatuo",
    "shen_lusu",
  ],
  shiji_yong: [
    "sp_wangshuang",
    "yuanhuan",
    "sp_huaman",
    "sp_zongyu",
    "sp_chendong",
    "sunyi",
    "sp_gaolan",
    "mb_shen_machao",
  ],
  shiji_yan: [
    "sp_cuiyan",
    "sp_zhangchangpu",
    "sp_jiangwan",
    "liuba",
    "sp_jiangqing",
    "sp_lvfan",
    "sp_huangfusong",
    "sp_zhujun",
    "mb_shen_jiangwei",
  ],
}

const characterSortTranslate = {
  shiji_zhi: "始计篇·智",
  shiji_xin: "始计篇·信",
  shiji_ren: "始计篇·仁",
  shiji_yong: "始计篇·勇",
  shiji_yan: "始计篇·严",
}

export { characterSort, characterSortTranslate }
